ifdef CONFIG_RHODE_DTB
	obj-$(CONFIG_SND_SMARTPA_AW882XX) += aw882xx.o
	aw882xx-objs += aw_init.o
	aw882xx-objs += aw_bin_parse.o
	aw882xx-objs += aw_calib.o
	aw882xx-objs += aw_device.o
	aw882xx-objs += aw_dsp.o
	aw882xx-objs += aw_monitor.o
endif
